### ISSUE TITLE
ImportError: cannot import name get_dataset_integ

### ISSUE THREAD

**Issue by mtoseef99** [ai4pm/TL4HDR#1]
In 

> ../examples/test.py

 the function `get_dataset_integ` is missing.

Please provide a solution to this issue. Thanks.

@AtlasGao ai4pm

**Comment by AtlasGao** [comment]
> In
> 
> > ../examples/test.py
> 
> the function `get_dataset_integ` is missing.
> 
> Please provide a solution to this issue. Thanks.
> 
> @AtlasGao ai4pm



> In
> 
> > ../examples/test.py
> 
> the function `get_dataset_integ` is missing.
> 
> Please provide a solution to this issue. Thanks.
> 
> @AtlasGao ai4pm

Hi Toseef99:

Thank you for your comment, and I have fixed this issue yesterday. Please recheck the file and let me know if you have any questions.
Best,
Yan
