### ISSUE TITLE
Could you share the mRNA.mat

### ISSUE THREAD

**Issue by Sophie52052** [ai4pm/TL4HDR#3]
Could you share the mRNA.mat
It seems only MMRF-AA-EA-mRNA-OS-3YR.mat in the dataset
There is some error, when i try to run "COAD" "DSS" "mRNA"
Thanks

**Comment by AtlasGao** [comment]
As shown in the instructions: 
"Note, the mRNA expression data of TCGA cohort can be downloaded from https://figshare.com/articles/dataset/Gao_Y_Cui_Y_2020_/12811574, and put it under the TL4RDH/data/datasets/" 
Best,
Yan
